# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/test/**"
    - "test/**"

linter:
  rules:
    errors:
      missing_return: error
      missing_required_param: error
      parameter_assignments: error
      type_annotate_public_apis: ignore
    exclude:
      - "**/*.g.dart"
      - "**/*.freezed.dart"
      - "**/*.config.dart"
