name: CD
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    name: Release Android To AppCenter
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Run build_runner
        run: flutter pub run build_runner build

      - name: Bump Build Number
        run: scripts/bump-build-number.sh

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'flutter_template_keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Set Flavor Name
        run: scripts/set-flavor-and-apk-path-to-env.sh

      - name: Build APK
        run: scripts/build.sh apk $FLAVOR_NAME --release --obfuscate --split-debug-info=debug-info
        env:
          KEY_STORE_PATH: ${{ steps.decode_keystore.outputs.filePath }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - name: Upload Artifact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: shounak-wednesday.is/Flutter-template-test-Android
          token: ${{ secrets.APP_CENTER_TOKEN }}
          group: testers
          file: ${{ env.APK_PATH }}
          notifyTesters: true

      - name: Add Tag Name to ENV
        run: scripts/gh-action-read-and-set-version-env.sh

      - name: Create Release and Add APK Artifact
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag_name }}
          files: |
            build/app/outputs/flutter-apk/app-qa-release.apk
            debug-info/app.android-arm.symbols
            debug-info/app.android-arm64.symbols
            debug-info/app.android-x64.symbols


  build-ios:
    name: Release iOS to TestFlight
    runs-on: macos-latest
    steps:
      - name: TO BE IMPLEMENTED
        run: echo "Workflow to be implemented"
#      - uses: actions/checkout@v2
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#      - name: Get Dependencies
#        run: flutter pub get
#      - name: Run build_runner
#        run: flutter pub run build_runner build
#      - name: Build iOS
#        run: scripts/build.sh ios qa --release --no-codesign

  commit-version-update:
    name: Commit Version Change
    runs-on: ubuntu-latest
    needs: [ build-android, build-ios ]
    if: |
      always() &&
      (needs.build-android.result == 'success' || needs.build-ios.result == 'success')
    steps:
      - uses: actions/checkout@v2

      - name: Bump Version
        run: scripts/bump-build-number.sh

      - name: Congifure Git
        run: |
          git config user.name "Github Actions CD"
          git config user.email "<>"

      - name: Commit Version Change
        run: scripts/commit-version.sh