name: CD
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
jobs:
  build-android:
    name: Deploy Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get Dependencies
        run: flutter pub get
      - name: Run build_runner
        run: flutter pub run build_runner build
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/flutter_template_keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}
      - name: Build APK
        run: scripts/build.sh apk qa --release
        env:
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      - name: Upload Artifact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: shounak-wednesday.is/Flutter-template-test-Android
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: testers
          file: build/app/outputs/flutter-apk/app-qa-release.apk
          notifyTesters: true
#  build-ios:
#    name: Deploy iOS
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#      - name: Get Dependencies
#        run: flutter pub get
#      - name: Run build_runner
#        run: flutter pub run build_runner build
#      - name: Build iOS
#        run: scripts/build.sh ios dev --debug --no-codesign