name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint-test-build:
    name: Lint, Test And Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get Dependencies
        run: flutter pub get
      - name: Lint
        run: flutter analyze --fatal-infos --fatal-warnings
      - name: Unit tests
        run: flutter test
      - name: Build
        run: flutter build apk --flavor dev -t lib/entrypoints/main_dev.dart --debug